### ISSUE TITLE
Add a conditioned links on next pages

### ISSUE THREAD

**Issue by abdulkadiret** [CodeYourFuture/project-quiz#20]
Add a conditioned links on next pages:

- Example: 
The landing page Navbar should include a logo on the left and “Quiz” centred in the middle. 

![landing-mob](https://user-images.githubusercontent.com/44118775/78164141-36d75780-7441-11ea-98ba-4a0005f47cf6.png)

**Comment by bonboh** [comment]
Is this issue still needed or can it be closed?

**Comment by abdulkadiret** [comment]
We do need it I think  it's a duplicate. On another ticket Vicky had already implemented it. Here is the link for that pull request: https://github.com/CodeYourFuture/project-quiz/pull/59
so we can close it I think. :)

**Comment by bonboh** [comment]
Great, closing the issue
