### ISSUE TITLE
Add quiz topic

### ISSUE THREAD

**Issue by viktoriia-kosenko** [CodeYourFuture/project-quiz#58]
Can be done after #55 
When user chooses different quiz, they can see also the quiz topic.
For example 

    CYF Quiz
    Topic :  HTML

**Comment by bonboh** [comment]
Is this issue still needed or can it be closed?

**Comment by viktoriia-kosenko** [comment]
No, we can close it I just don't know how to do it

**Comment by bonboh** [comment]
Ah, maybe only I have the power!
